/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TextSkeletonLoader {
    'loading': boolean;
  }
}

declare global {


  interface HTMLTextSkeletonLoaderElement extends Components.TextSkeletonLoader, HTMLStencilElement {}
  var HTMLTextSkeletonLoaderElement: {
    prototype: HTMLTextSkeletonLoaderElement;
    new (): HTMLTextSkeletonLoaderElement;
  };
  interface HTMLElementTagNameMap {
    'text-skeleton-loader': HTMLTextSkeletonLoaderElement;
  }
}

declare namespace LocalJSX {
  interface TextSkeletonLoader {
    'loading'?: boolean;
  }

  interface IntrinsicElements {
    'text-skeleton-loader': TextSkeletonLoader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'text-skeleton-loader': LocalJSX.TextSkeletonLoader & JSXBase.HTMLAttributes<HTMLTextSkeletonLoaderElement>;
    }
  }
}


